/* Greyfusion Limited — seed script. Run: npm run db:seed */
import path from "node:path";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { scryptSync, randomBytes } from "node:crypto";

function hashPassword(password: string): string {
  const salt = randomBytes(16).toString("hex");
  return `${salt}:${scryptSync(password, salt, 64).toString("hex")}`;
}

const dbPath = (process.env.DATABASE_URL ?? "file:./prisma/dev.db").replace(/^file:/, "");
const adapter = new PrismaBetterSqlite3({ url: path.isAbsolute(dbPath) ? dbPath : path.join(process.cwd(), dbPath) });
const prisma = new PrismaClient({ adapter });

const day = 86_400_000;
const now = Date.now();
const d = (offsetDays: number) => new Date(now + offsetDays * day);

const vehicles = [
  { slug: "byd-dolphin", make: "BYD", model: "Dolphin", year: 2026, powertrain: "BEV", bodyStyle: "Hatchback", priceNGN: 28_500_000, rangeKm: 340, batteryKwh: 44.9, accel: 10.9, chargeKw: 60, chargeTime: "30–80% in 29 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Coral Pink", hex: "#E8A9B0" }, { name: "Surf Blue", hex: "#5B8DB8" }, { name: "Polar White", hex: "#E8EAED" }]), summary: "The sensible first EV: compact, efficient and cheap to run. Real-world 340km covers a week of Abuja commuting on one charge.", featured: true },
  { slug: "mg4-ev", make: "MG", model: "MG4 EV", year: 2025, powertrain: "BEV", bodyStyle: "Hatchback", priceNGN: 32_000_000, rangeKm: 435, batteryKwh: 64, accel: 7.9, chargeKw: 140, chargeTime: "10–80% in 26 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Volcano Orange", hex: "#E2583E" }, { name: "Black Pearl", hex: "#22262C" }, { name: "Dover White", hex: "#E8EAED" }]), summary: "Rear-driven, sharp to steer, and the quickest-charging car under ₦35M. The enthusiast's budget EV.", featured: false },
  { slug: "byd-atto-3", make: "BYD", model: "Atto 3", year: 2026, powertrain: "BEV", bodyStyle: "SUV", priceNGN: 38_000_000, rangeKm: 420, batteryKwh: 60.5, accel: 7.3, chargeKw: 88, chargeTime: "30–80% in 29 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Forest Green", hex: "#3E5E4C" }, { name: "Ski White", hex: "#E8EAED" }, { name: "Parkour Red", hex: "#B33A2E" }]), summary: "The family-SUV default. Blade battery, generous cabin, and ground clearance that respects Nigerian estate roads.", featured: true },
  { slug: "toyota-corolla-cross-hybrid", make: "Toyota", model: "Corolla Cross Hybrid", year: 2026, powertrain: "HEV", bodyStyle: "SUV", priceNGN: 42_000_000, rangeKm: 850, batteryKwh: 1.3, accel: 11.0, chargeKw: 0, chargeTime: "Self-charging hybrid — no plug", seats: 5, colors: JSON.stringify([{ name: "Celestite Grey", hex: "#8B939E" }, { name: "Attitude Black", hex: "#1A1D22" }, { name: "Platinum White", hex: "#E8EAED" }]), summary: "No plug, no anxiety: 4.3L/100km in traffic and Toyota's hybrid system with a decade of tropical proof behind it.", featured: true },
  { slug: "hyundai-kona-electric", make: "Hyundai", model: "Kona Electric", year: 2026, powertrain: "BEV", bodyStyle: "SUV", priceNGN: 45_000_000, rangeKm: 490, batteryKwh: 65.4, accel: 7.8, chargeKw: 102, chargeTime: "10–80% in 41 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Abyss Black", hex: "#1A1D22" }, { name: "Atlas White", hex: "#E8EAED" }, { name: "Neoteric Yellow", hex: "#D9C756" }]), summary: "490km of range and Hyundai's 8-year battery warranty. The long-legged crossover for interstate drivers.", featured: false },
  { slug: "byd-seal", make: "BYD", model: "Seal RWD", year: 2026, powertrain: "BEV", bodyStyle: "Sedan", priceNGN: 52_000_000, rangeKm: 570, batteryKwh: 82.5, accel: 5.9, chargeKw: 150, chargeTime: "30–80% in 26 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Arctic Blue", hex: "#7FA8C9" }, { name: "Cosmos Black", hex: "#1A1D22" }, { name: "Aurora White", hex: "#E8EAED" }]), summary: "Cell-to-body structure, 570km range, and executive-sedan composure. Our best-selling EV to private buyers.", featured: true },
  { slug: "hyundai-tucson-phev", make: "Hyundai", model: "Tucson PHEV", year: 2025, powertrain: "PHEV", bodyStyle: "SUV", priceNGN: 55_000_000, rangeKm: 800, batteryKwh: 13.8, accel: 8.2, chargeKw: 7, chargeTime: "Full charge in 2h (AC wallbox)", seats: 5, colors: JSON.stringify([{ name: "Amazon Grey", hex: "#5B6470" }, { name: "White Cream", hex: "#E8EAED" }, { name: "Deep Sea", hex: "#2F4858" }]), summary: "62km of silent electric commuting, petrol freedom for the East trip. The both-worlds machine.", featured: false },
  { slug: "toyota-camry-hybrid", make: "Toyota", model: "Camry Hybrid", year: 2026, powertrain: "HEV", bodyStyle: "Sedan", priceNGN: 58_000_000, rangeKm: 900, batteryKwh: 1.6, accel: 7.8, chargeKw: 0, chargeTime: "Self-charging hybrid — no plug", seats: 5, colors: JSON.stringify([{ name: "Precious Metal", hex: "#8B939E" }, { name: "Midnight Black", hex: "#1A1D22" }, { name: "Emotional Red", hex: "#B33A2E" }]), summary: "The director's car, reinvented: 900km per tank, near-silent pull-away, and legendary resale value.", featured: false },
  { slug: "nissan-ariya", make: "Nissan", model: "Ariya", year: 2025, powertrain: "BEV", bodyStyle: "SUV", priceNGN: 62_000_000, rangeKm: 500, batteryKwh: 87, accel: 7.6, chargeKw: 130, chargeTime: "10–80% in 35 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Aurora Green", hex: "#4C6B5C" }, { name: "Burgundy", hex: "#6B2E3E" }, { name: "Pearl White", hex: "#E8EAED" }]), summary: "A lounge on wheels — flat floor, haptic cabin, 500km range. Quietly one of the best-built EVs on sale.", featured: false },
  { slug: "kia-ev6", make: "Kia", model: "EV6", year: 2026, powertrain: "BEV", bodyStyle: "Crossover", priceNGN: 68_000_000, rangeKm: 528, batteryKwh: 77.4, accel: 5.2, chargeKw: 240, chargeTime: "10–80% in 18 min (350kW DC)", seats: 5, colors: JSON.stringify([{ name: "Runway Red", hex: "#B33A2E" }, { name: "Moonscape", hex: "#5B6470" }, { name: "Snow White", hex: "#E8EAED" }]), summary: "800-volt architecture: 18 minutes to 80% on a fast charger. The one that makes petrol feel slow twice.", featured: true },
  { slug: "tesla-model-3", make: "Tesla", model: "Model 3 RWD", year: 2025, powertrain: "BEV", bodyStyle: "Sedan", priceNGN: 75_000_000, rangeKm: 513, batteryKwh: 60, accel: 6.1, chargeKw: 170, chargeTime: "10–80% in 27 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Pearl White", hex: "#E8EAED" }, { name: "Deep Blue", hex: "#2F4470" }, { name: "Solid Black", hex: "#1A1D22" }]), summary: "Software-first driving with the efficiency benchmark of the class. Imported to order, fully warranted by us.", featured: false },
  { slug: "mercedes-eqe-350", make: "Mercedes-Benz", model: "EQE 350+", year: 2025, powertrain: "BEV", bodyStyle: "Sedan", priceNGN: 95_000_000, rangeKm: 620, batteryKwh: 89, accel: 6.4, chargeKw: 170, chargeTime: "10–80% in 32 min (DC)", seats: 5, colors: JSON.stringify([{ name: "Obsidian Black", hex: "#1A1D22" }, { name: "High-tech Silver", hex: "#B8BEC6" }, { name: "Sodalite Blue", hex: "#2F4470" }]), summary: "620km of range wrapped in S-Class hush. The chairman's statement that boards can defend.", featured: true },
];

const properties = [
  { slug: "wuse-atrium-2bed", title: "The Wuse Atrium — 2-Bed Executive Shortlet", type: "shortlet", location: "Wuse 2", city: "Abuja", priceNGN: 0, nightlyNGN: 145_000, serviceNGN: 0, depositNGN: 0, cautionNGN: 100_000, beds: 2, baths: 2, sqm: 92, amenities: JSON.stringify(["24/7 power (solar hybrid)", "Starlink WiFi", "Smart lock entry", "Netflix + DSTV", "Gym access", "Daily housekeeping option", "Secure parking", "CCTV estate"]), summary: "Our flagship shortlet: a 92m² two-bed in the Wuse Atrium with hybrid solar power that has not blinked in 14 months. Four minutes from Emab Plaza, walkable to Wuse 2's restaurant strip.", featured: true },
  { slug: "wuse-atrium-studio", title: "The Wuse Atrium — Studio Suite", type: "shortlet", location: "Wuse 2", city: "Abuja", priceNGN: 0, nightlyNGN: 85_000, serviceNGN: 0, depositNGN: 0, cautionNGN: 50_000, beds: 1, baths: 1, sqm: 48, amenities: JSON.stringify(["24/7 power (solar hybrid)", "Fibre WiFi", "Smart TV", "Kitchenette", "Secure parking", "Weekly housekeeping"]), summary: "A compact, quiet studio for business travel — desk with monitor, blackout curtains and coffee that respects your 7am call.", featured: false },
  { slug: "vi-skyline-3bed", title: "Skyline Residence — 3-Bed Waterview Shortlet", type: "shortlet", location: "Victoria Island", city: "Lagos", priceNGN: 0, nightlyNGN: 250_000, serviceNGN: 0, depositNGN: 0, cautionNGN: 150_000, beds: 3, baths: 3, sqm: 160, amenities: JSON.stringify(["Lagoon view", "Inverter + gen backup", "Concierge 24/7", "Pool + gym", "Chef on request", "Airport pickup", "Secure parking"]), summary: "160m² on the 11th floor with a lagoon view that resets your cortisol. Hosts board retreats, film crews and families who outgrew hotels.", featured: true },
  { slug: "gra-ph-shortlet", title: "Garden City Loft — 1-Bed Shortlet", type: "shortlet", location: "GRA Phase 2", city: "Port Harcourt", priceNGN: 0, nightlyNGN: 95_000, serviceNGN: 0, depositNGN: 0, cautionNGN: 60_000, beds: 1, baths: 1, sqm: 64, amenities: JSON.stringify(["24/7 power", "Fibre WiFi", "Washer/dryer", "Secure estate", "Housekeeping"]), summary: "The PH crew-change favourite: five minutes from Trans-Amadi, laundry in-unit, and power that survives the grid.", featured: false },
  { slug: "katampe-terrace-4bed", title: "Katampe Terrace — 4-Bed Terrace Duplex", type: "residential", location: "Katampe Extension", city: "Abuja", priceNGN: 9_500_000, nightlyNGN: 0, serviceNGN: 850_000, depositNGN: 1_000_000, cautionNGN: 500_000, beds: 4, baths: 5, sqm: 240, amenities: JSON.stringify(["All rooms en-suite", "BQ", "Solar-ready roof", "Estate security", "Green area", "Borehole water"]), summary: "240m² of family logic: all-en-suite rooms, a proper BQ, and an estate that enforces its service charge. Diplomatic-zone quiet, mainland pricing.", featured: true },
  { slug: "gwarinpa-3bed-flat", title: "6th Avenue Court — 3-Bed Flat", type: "residential", location: "Gwarinpa", city: "Abuja", priceNGN: 4_200_000, nightlyNGN: 0, serviceNGN: 350_000, depositNGN: 400_000, cautionNGN: 200_000, beds: 3, baths: 3, sqm: 130, amenities: JSON.stringify(["POP finishing", "Fitted kitchen", "Car port ×2", "Water treatment", "Gated close"]), summary: "A clean, honestly-priced 3-bed in Gwarinpa's most liquid rental corridor. Ready for immediate move-in.", featured: false },
  { slug: "lekki-2bed-flat", title: "Marwa Gardens — 2-Bed Apartment", type: "residential", location: "Lekki Phase 1", city: "Lagos", priceNGN: 7_800_000, nightlyNGN: 0, serviceNGN: 1_200_000, depositNGN: 650_000, cautionNGN: 400_000, beds: 2, baths: 2, sqm: 105, amenities: JSON.stringify(["24/7 estate power", "Pool + gym", "Elevator", "Concierge", "Visitor parking"]), summary: "Phase 1 without the flood stories: raised development, serviced to an actual standard, five minutes from the toll gate.", featured: false },
  { slug: "asokoro-5bed-detached", title: "Asokoro Ridge — 5-Bed Detached + Pool", type: "residential", location: "Asokoro", city: "Abuja", priceNGN: 15_000_000, nightlyNGN: 0, serviceNGN: 1_500_000, depositNGN: 2_000_000, cautionNGN: 1_000_000, beds: 5, baths: 6, sqm: 420, amenities: JSON.stringify(["Private pool", "2-room BQ", "Study + cinema", "Full solar system", "Panic room", "Landscaped 1,100m² plot"]), summary: "A 420m² statement on Asokoro ridge with a full Greyfusion solar installation — the power bill is a rounding error.", featured: true },
  { slug: "wuse-office-floor", title: "Emab Corridor — 380m² Office Floor", type: "commercial", location: "Wuse 2", city: "Abuja", priceNGN: 18_000_000, nightlyNGN: 0, serviceNGN: 2_400_000, depositNGN: 3_000_000, cautionNGN: 1_500_000, beds: 0, baths: 4, sqm: 380, amenities: JSON.stringify(["Open floor plate", "3-phase + inverter backup", "2 passenger lifts", "40 parking bays (shared)", "Fibre from 2 providers"]), summary: "An uninterrupted 380m² floor plate in the Emab commercial corridor — fit out to your plan, power and fibre already solved.", featured: false },
  { slug: "vi-retail-unit", title: "Adeola Odeku — Prime Retail Unit", type: "commercial", location: "Victoria Island", city: "Lagos", priceNGN: 22_000_000, nightlyNGN: 0, serviceNGN: 2_800_000, depositNGN: 3_500_000, cautionNGN: 1_800_000, beds: 0, baths: 2, sqm: 210, amenities: JSON.stringify(["12m street frontage", "Double-height ceiling", "Dedicated transformer", "Loading bay", "Signage rights"]), summary: "210m² with twelve metres of Adeola Odeku frontage. Footfall you can bank, signage rights included.", featured: false },
  { slug: "idu-warehouse-1200", title: "Idu Industrial — 1,200m² Warehouse", type: "warehousing", location: "Idu Industrial District", city: "Abuja", priceNGN: 14_500_000, nightlyNGN: 0, serviceNGN: 900_000, depositNGN: 2_000_000, cautionNGN: 1_000_000, beds: 0, baths: 2, sqm: 1200, amenities: JSON.stringify(["9m eaves height", "2 dock levellers", "40-tonne access road", "Fire hydrant system", "Fenced yard 2,000m²", "24/7 security"]), summary: "1,200m² clear-span with 9m eaves and rail-corridor logistics access. FMCG and pharma tenants next door.", featured: false },
  { slug: "trans-amadi-warehouse", title: "Trans-Amadi — 800m² Warehouse + Yard", type: "warehousing", location: "Trans-Amadi", city: "Port Harcourt", priceNGN: 11_000_000, nightlyNGN: 0, serviceNGN: 700_000, depositNGN: 1_500_000, cautionNGN: 800_000, beds: 0, baths: 2, sqm: 800, amenities: JSON.stringify(["7.5m eaves", "Gantry-crane ready", "Oil & gas zone proximity", "Hardstanding yard", "Security post"]), summary: "800m² in the heart of PH's industrial engine — crane-ready structure, laydown yard, and the address your logistics team wants.", featured: false },
];

const products = [
  { slug: "gf-p580m-panel", name: "GF-P580M 580W TOPCon Bifacial Panel", category: "solar", priceNGN: 185_000, stock: 240, variants: JSON.stringify([{ label: "Pack", options: ["Single", "Pallet of 36"] }]), specs: JSON.stringify([{ k: "Rated power", v: "580Wp" }, { k: "Efficiency", v: "22.6%" }, { k: "Cell type", v: "N-type TOPCon bifacial" }, { k: "Warranty", v: "30-yr linear / 12-yr product" }, { k: "Dimensions", v: "2278 × 1134 × 30 mm" }]), summary: "Our flagship utility-grade module — the same panel on the Zenith Agro plant roof.", featured: true },
  { slug: "gf-p450m-panel", name: "GF-P450M 450W Mono PERC Panel", category: "solar", priceNGN: 120_000, stock: 380, variants: JSON.stringify([{ label: "Pack", options: ["Single", "Pallet of 31"] }]), specs: JSON.stringify([{ k: "Rated power", v: "450Wp" }, { k: "Efficiency", v: "21.3%" }, { k: "Warranty", v: "25-yr linear" }]), summary: "The residential workhorse: proven PERC cells at the best naira-per-watt in our catalogue.", featured: false },
  { slug: "gf-bat-15k", name: "GF-BAT-15K 15.36kWh LiFePO₄ Battery", category: "solar", priceNGN: 6_900_000, stock: 18, variants: JSON.stringify([{ label: "Comms", options: ["CAN", "RS485"] }]), specs: JSON.stringify([{ k: "Capacity", v: "15.36 kWh" }, { k: "Chemistry", v: "LiFePO₄" }, { k: "Cycle life", v: "6,000 @ 80% DoD" }, { k: "Peak discharge", v: "150A" }, { k: "Warranty", v: "10 years" }]), summary: "Rack-mount storage engineered for 35°C ambient — the backbone of our hybrid installs.", featured: true },
  { slug: "gf-bat-5k", name: "GF-BAT-5K 5.12kWh Wall-Mount Battery", category: "solar", priceNGN: 2_450_000, stock: 42, variants: JSON.stringify([{ label: "Colour", options: ["Graphite", "White"] }]), specs: JSON.stringify([{ k: "Capacity", v: "5.12 kWh" }, { k: "Chemistry", v: "LiFePO₄" }, { k: "Cycle life", v: "6,000 @ 80% DoD" }, { k: "Stackable", v: "Up to 6 units (30.7 kWh)" }]), summary: "Start with one, stack to six. The apartment-friendly battery that grows with your load.", featured: false },
  { slug: "gf-inv-10k", name: "GF-INV-10K 10kW Hybrid Inverter", category: "inverters", priceNGN: 4_800_000, stock: 14, variants: JSON.stringify([{ label: "Phase", options: ["Single-phase", "Three-phase"] }]), specs: JSON.stringify([{ k: "Rated output", v: "10 kW" }, { k: "Max efficiency", v: "97.6%" }, { k: "MPPT", v: "2 trackers, 22A each" }, { k: "Parallel", v: "Up to 10 units" }, { k: "Warranty", v: "5 years (ext. to 10)" }]), summary: "Whole-home or light-commercial hybrid with generator input and UPS-grade 10ms transfer.", featured: true },
  { slug: "gf-inv-6k", name: "GF-INV-6K 6kW Hybrid Inverter", category: "inverters", priceNGN: 2_400_000, stock: 26, variants: JSON.stringify([{ label: "Phase", options: ["Single-phase"] }]), specs: JSON.stringify([{ k: "Rated output", v: "6 kW" }, { k: "Max efficiency", v: "97.3%" }, { k: "MPPT", v: "2 trackers" }, { k: "Warranty", v: "5 years" }]), summary: "The 3-bedroom sweet spot: runs ACs on solar by day, silent battery power by night.", featured: false },
  { slug: "gf-inv-3-5k", name: "GF-INV-3.5K 3.5kVA Hybrid Inverter", category: "inverters", priceNGN: 1_350_000, stock: 3, variants: JSON.stringify([{ label: "Phase", options: ["Single-phase"] }]), specs: JSON.stringify([{ k: "Rated output", v: "3.5 kVA" }, { k: "Max efficiency", v: "96.8%" }, { k: "Warranty", v: "3 years" }]), summary: "Entry-level hybrid for flats and small offices — fridge, lights, WiFi and TV without drama.", featured: false },
  { slug: "gf-mount-kit", name: "Roof Mounting Kit (8-Panel, Pitched)", category: "solar", priceNGN: 165_000, stock: 55, variants: JSON.stringify([{ label: "Roof", options: ["Aluzinc longspan", "Stone-coated", "Concrete"] }]), specs: JSON.stringify([{ k: "Capacity", v: "8 panels" }, { k: "Material", v: "Anodised aluminium" }, { k: "Wind rating", v: "160 km/h" }]), summary: "Rails, mid/end clamps and roof hooks — everything between panel and roof, engineered as a kit.", featured: false },
  { slug: "gf-tv-65-qled", name: 'Fusion View 65" QLED 4K Smart TV', category: "electronics", priceNGN: 1_250_000, stock: 12, variants: JSON.stringify([{ label: "Size", options: ['55"', '65"', '75"'] }]), specs: JSON.stringify([{ k: "Panel", v: "QLED 4K 120Hz" }, { k: "OS", v: "Google TV" }, { k: "Power draw", v: "140W typical — inverter friendly" }]), summary: "Cinema-grade QLED chosen for low power draw — pairs beautifully with battery evenings.", featured: false },
  { slug: "gf-laptop-pro14", name: "FusionBook Pro 14 (Ultra 7 / 32GB / 1TB)", category: "electronics", priceNGN: 1_850_000, stock: 9, variants: JSON.stringify([{ label: "RAM/Storage", options: ["16GB / 512GB", "32GB / 1TB"] }]), specs: JSON.stringify([{ k: "CPU", v: "Intel Core Ultra 7" }, { k: "Display", v: '14" 2.8K OLED' }, { k: "Battery", v: "70Wh — full workday" }, { k: "Warranty", v: "2 years on-site (Abuja/Lagos)" }]), summary: "The consultant's machine: OLED clarity, all-day battery, and on-site warranty service.", featured: false },
  { slug: "gf-earbuds-anc", name: "Fusion Buds ANC Pro", category: "electronics", priceNGN: 145_000, stock: 60, variants: JSON.stringify([{ label: "Colour", options: ["Graphite", "White", "Vermilion"] }]), specs: JSON.stringify([{ k: "ANC", v: "-42dB adaptive" }, { k: "Battery", v: "8h + 24h case" }, { k: "Rating", v: "IPX5" }]), summary: "Generator hum, cancelled. Our best-selling stocking-filler for open-plan sanity.", featured: false },
  { slug: "gf-cam-kit4", name: "SecureSight 4-Camera PoE Kit", category: "smart-home", priceNGN: 385_000, stock: 21, variants: JSON.stringify([{ label: "Storage", options: ["1TB NVR", "2TB NVR"] }]), specs: JSON.stringify([{ k: "Resolution", v: "4MP colour night vision" }, { k: "Power", v: "PoE — one cable per camera" }, { k: "App", v: "iOS/Android with offline recording" }]), summary: "Four 4MP PoE cameras plus NVR, installed in a day. Works through NEPA outages on 30W.", featured: true },
  { slug: "gf-smart-lock", name: "GateGuard Smart Lock (Fingerprint + App)", category: "smart-home", priceNGN: 185_000, stock: 34, variants: JSON.stringify([{ label: "Finish", options: ["Matte black", "Brushed steel"] }]), specs: JSON.stringify([{ k: "Access", v: "Fingerprint, PIN, card, app, key" }, { k: "Battery", v: "8,000 openings per charge" }, { k: "Rating", v: "IP65 outdoor" }]), summary: "Five ways in for you, none for anyone else. The shortlet operator's favourite.", featured: false },
  { slug: "gf-video-doorbell", name: "GateGuard Video Doorbell Pro", category: "smart-home", priceNGN: 145_000, stock: 30, variants: JSON.stringify([{ label: "Power", options: ["Wired", "Battery"] }]), specs: JSON.stringify([{ k: "Resolution", v: "2K HDR, 160° view" }, { k: "Talk", v: "Two-way, noise-cancelled" }, { k: "Storage", v: "Local SD + encrypted cloud" }]), summary: "See and speak to the gate from anywhere — pairs with GateGuard locks for one-tap entry.", featured: false },
  { slug: "gf-ac-controller", name: "FusionSense Smart AC Controller", category: "smart-home", priceNGN: 95_000, stock: 48, variants: JSON.stringify([{ label: "Pack", options: ["Single", "3-pack"] }]), specs: JSON.stringify([{ k: "Compatibility", v: "Any remote-controlled split AC" }, { k: "Sensing", v: "Temp + humidity + occupancy" }, { k: "Savings", v: "Up to 30% cooling energy" }]), summary: "Turns any split AC into a scheduled, occupancy-aware smart unit — the cheapest kWh is the one you don't cool an empty room with.", featured: false },
  { slug: "gf-mesh-wifi", name: "FusionMesh WiFi 6 (3-Pack)", category: "smart-home", priceNGN: 295_000, stock: 27, variants: JSON.stringify([{ label: "Pack", options: ["2-pack", "3-pack"] }]), specs: JSON.stringify([{ k: "Standard", v: "WiFi 6 AX3000" }, { k: "Coverage", v: "Up to 550m²" }, { k: "Backhaul", v: "Wired or wireless" }]), summary: "Dead zones die here. Duplex-wide coverage with roaming that video calls don't notice.", featured: false },
  { slug: "gf-rack-server", name: "FusionEdge R2 Rack Server (Xeon / 64GB)", category: "enterprise", priceNGN: 4_200_000, stock: 5, variants: JSON.stringify([{ label: "Config", options: ["Xeon Silver / 64GB / 4×2TB", "Xeon Gold / 128GB / 8×2TB"] }]), specs: JSON.stringify([{ k: "Form factor", v: "2U rack" }, { k: "PSU", v: "Dual hot-swap 800W" }, { k: "Warranty", v: "3-yr NBD on-site" }]), summary: "On-prem compute for banks and agencies that keep data in-country. Deployed by our IT division.", featured: false },
  { slug: "gf-ups-3kva", name: "PowerBridge 3kVA Online UPS", category: "enterprise", priceNGN: 850_000, stock: 16, variants: JSON.stringify([{ label: "Runtime", options: ["Internal batteries", "External bank ready"] }]), specs: JSON.stringify([{ k: "Topology", v: "Double-conversion online" }, { k: "Transfer", v: "0ms" }, { k: "Output", v: "Pure sine wave" }]), summary: "Zero-millisecond transfer for server rooms and medical equipment. NEPA never touches your load.", featured: false },
  { slug: "gf-switch-48", name: "FusionNet 48-Port PoE+ Managed Switch", category: "enterprise", priceNGN: 620_000, stock: 0, variants: JSON.stringify([{ label: "Uplink", options: ["4×10G SFP+"] }]), specs: JSON.stringify([{ k: "Ports", v: "48 × GbE PoE+ (740W budget)" }, { k: "Management", v: "L2+ CLI/Web" }, { k: "Warranty", v: "Limited lifetime" }]), summary: "One switch for the whole floor — cameras, APs and phones on a single PoE budget.", featured: false },
];

const projects = [
  { slug: "karu-jikwoyi-dual-carriageway", title: "Karu–Jikwoyi Dual Carriageway", sector: "Roads & Highways", status: "Completed", location: "FCT, Abuja", valueBand: "₦8B – ₦12B", year: 2024, client: "FCT Ministry of Works", summary: "9.6km of dual carriageway with 14 box culverts, solar street lighting and pedestrian infrastructure, delivered through two rainy seasons without a single lost-time incident.", challenge: "The corridor crosses three seasonal streams and carried live traffic of 22,000 vehicles daily. Conventional phasing would have closed the route for eight months — politically and economically unacceptable — while lateritic subgrade CBR values as low as 4% ruled out standard pavement design.", solution: "We ran night-shift half-carriageway construction with precast box culverts cast off-site, cutting stream-crossing closures to 72 hours each. The pavement was redesigned as cement-stabilised subbase over geogrid, lifting effective CBR above 30% and shaving ₦640M off the earthworks bill — savings returned to the client against solar lighting." },
  { slug: "zenith-agro-microgrid", title: "Zenith Agro 2.4MW Hybrid Micro-Grid", sector: "Industrial / Energy", status: "Completed", location: "Kaduna State", valueBand: "₦2.5B – ₦4B", year: 2025, client: "Zenith Agro Group", summary: "A 2.4MWp solar array with 4.8MWh of storage and synchronised 1.5MVA generator backup powering a rice-processing complex — 99.2% uptime since commissioning.", challenge: "Milling loads spike 6× in under a second when hullers engage, which collapses conventional inverter-led grids. Diesel gensets ran 22 hours daily at ₦38M monthly, and the 33kV feeder averaged eleven outages a week.", solution: "Our energy division specified grid-forming inverters with 2C-rated battery strings to absorb motor inrush, while the construction division delivered the substation and cable trenching as one contract. Generator runtime fell to 90 minutes a day; the plant's energy cost per tonne of rice dropped 63%." },
  { slug: "meridian-hq-fitout", title: "Meridian Trust Bank — HQ Structural Retrofit", sector: "Commercial Buildings", status: "Completed", location: "Central Business District, Abuja", valueBand: "₦1B – ₦2.5B", year: 2023, client: "Meridian Trust Bank", summary: "Structural strengthening and full MEP replacement of a 9-storey banking headquarters — occupied throughout, zero branch downtime.", challenge: "A 2001-era frame showed carbonation-induced rebar corrosion in 40% of sampled columns, but the bank could not vacate: trading floors and the data centre had to run through construction with vibration limits of 2mm/s.", solution: "Carbon-fibre wrapping and low-vibration hydro-demolition let us strengthen columns floor by floor at night. The data centre was migrated to an interim modular room built by our IT division in the car park — then back — with switchovers during trading holidays. Handover came in 11 days early." },
  { slug: "idu-logistics-park", title: "Idu Rail-Linked Logistics Park — Phase 1", sector: "Industrial / Warehousing", status: "Ongoing", location: "Idu, Abuja", valueBand: "₦4B – ₦8B", year: 2026, client: "Harmattan Foods / GF Real Estate JV", summary: "Four 1,200m² clear-span warehouses with rail siding access, 40-tonne pavements and a 600kWp solar canopy — Phase 1 of a 12-unit park.", challenge: "Black cotton soil across 60% of the site swells and shrinks seasonally, historically condemning Idu slabs to early failure, while the programme demanded steel erection to start before the rains.", solution: "We excavated and replaced 1.2m of expansive clay with cement-stabilised laterite under a monolithic post-tensioned slab — faster and 18% cheaper than piling. Steel packages were fabricated in parallel in Kaduna, letting erection begin nine days after slab cure." },
  { slug: "unity-mfb-branch-rollout", title: "Unity MicroFinance — 12-Branch Design-Build", sector: "Commercial Buildings", status: "Completed", location: "Nationwide (6 states)", valueBand: "₦1B – ₦2.5B", year: 2024, client: "Unity MicroFinance Bank", summary: "Twelve identical 280m² branch buildings delivered across six states in 40 weeks using a kit-of-parts design — every branch solar-powered from day one.", challenge: "Identical branches, wildly different sites: soil conditions from Sokoto sand to Bayelsa swamp, six state approval regimes, and a hard CBN licensing deadline that fined the client per late branch.", solution: "One structural kit, three foundation variants pre-engineered per soil class. Regional subcontractor cells from our 240-firm bench built four branches each while a flying QA team enforced a single standard. All twelve passed CBN inspection first time; the client's fine exposure: zero." },
  { slug: "eko-atlantic-office-struct", title: "Delta Deepwater Services — Operations Base", sector: "Oil & Gas Infrastructure", status: "Ongoing", location: "Onne, Rivers State", valueBand: "₦2.5B – ₦4B", year: 2026, client: "Delta Deepwater Services", summary: "A marine-grade operations base: 3-storey office block, 900m² workshop with 20-tonne overhead crane, and chloride-resistant concrete throughout.", challenge: "Salt-laden air and a high water table demanded durability detailing beyond standard practice; the client's insurers required a 50-year design life certification on the crane runway beams.", solution: "We specified GGBS-blended concrete with 60mm cover and stainless rebar in splash zones, validated by 90-day chloride migration testing. Crane runways were designed to Eurocode fatigue class with third-party certification from the outset — insurance sign-off came without a single query." },
  { slug: "wuse-atrium-development", title: "The Wuse Atrium Residences", sector: "Residential Development", status: "Completed", location: "Wuse 2, Abuja", valueBand: "₦2.5B – ₦4B", year: 2023, client: "Greyfusion Real Estate", summary: "Our own 38-unit residential development: build-to-rent apartments over retail, hybrid solar power plant, and 96% occupancy since opening.", challenge: "As both developer and contractor we set ourselves a brutal brief: hotel-grade uptime on power and water in central Abuja at rents the upper-middle market would actually pay — with a 20-month construction window on a tight urban site.", solution: "A 210kWp rooftop array with 430kWh storage was designed into the structure, not bolted on, cutting diesel to a backup role. Modular bathroom pods manufactured off-site saved 11 weeks. The building now serves as our permanent proof-of-concept — prospective clients tour it weekly." },
  { slug: "gwagwalada-water-scheme", title: "Gwagwalada Township Water Reticulation", sector: "Water Infrastructure", status: "Completed", location: "Gwagwalada, FCT", valueBand: "₦1B – ₦2.5B", year: 2022, client: "FCT Water Board", summary: "42km of HDPE reticulation, two 1,500m³ elevated tanks and 3,800 metered connections serving a township of 90,000.", challenge: "Legacy asbestos-cement mains had a 60% loss rate and undocumented routing; excavation risked cutting the very supply residents depended on during works.", solution: "We ran new HDPE mains in parallel corridors with night-time tie-ins zone by zone, keeping supply live throughout. GIS as-builts and district metering were handed over with the works — the Board now measures losses below 12% and bills what it pumps." },
];

const tenders = [
  { refNo: "GF-RFP-2026-014", title: "Supply of 1,200 tonnes of reinforcement steel (BS4449 B500B)", category: "Supply — Steel & Rebar", closingDate: d(5), status: "OPEN", description: "Supply and delivery of high-yield deformed bars (12mm–32mm) to the Idu Logistics Park site in three call-off batches between September and December 2026. Mill certificates and SONCAP required. Bid security: 2% bank guarantee." },
  { refNo: "GF-RFP-2026-015", title: "Subcontract: 4.2km stormwater drainage — Idu Logistics Park", category: "Civil Works", closingDate: d(12), status: "OPEN", description: "Precast U-drain supply and installation including excavation in stabilised laterite, 900mm–1500mm sections, with 14-week programme. COREN-supervised QA; plant schedule to accompany bid." },
  { refNo: "GF-RFP-2026-016", title: "O&M subcontract: 14 commercial solar sites (Abuja cluster)", category: "Energy Services", closingDate: d(21), status: "OPEN", description: "Two-year operations and maintenance of 14 grid-tied and hybrid sites totalling 3.1MWp: quarterly IV-curve tracing, thermal inspection, inverter servicing and 4-hour fault response SLA. NIMASA-style penalty regime applies." },
  { refNo: "GF-RFP-2026-017", title: "Framework: HVAC installation partners (Abuja / Lagos / PH)", category: "Mechanical / HVAC", closingDate: d(30), status: "OPEN", description: "Three-year framework for VRF and ducted-split installation across commercial fit-out projects. Applicants must show OEM certification (Daikin, LG or Midea) and at least three completed projects above ₦120M." },
  { refNo: "GF-RFP-2026-012", title: "Supply of 3,000 solar street-lighting poles with fittings", category: "Supply — Electrical", closingDate: d(3), status: "OPEN", description: "Galvanised 9m poles with 80W integrated solar luminaires for highway projects, delivered to Abuja and Kaduna depots. Type-test certificates and 5-year warranty mandatory. Closing imminent — late bids will not be opened." },
  { refNo: "GF-RFP-2026-009", title: "Haulage framework: heavy plant mobilisation (nationwide)", category: "Plant Hire / Logistics", closingDate: d(45), status: "OPEN", description: "National framework agreement for lowbed trailers (30T–75T) and crane trucks to support infrastructure deployment across six geopolitical zones. Telematics tracking and ISO 45001 compliance mandatory." }
];

async function main() {
  console.log("Seeding database (idempotent upsert)...");

  // 1. Seed Admin User
  const adminPassword = hashPassword("olu@12345");
  await prisma.user.update({
    where: { email: "olumide@greyfusion.com.ng" },
    update: {},
    create: {
      email: "admin@greyfusion.com.ng",
      name: "Greyfusion Admin",
      password: adminPassword,
      role: "ADMIN",
    },
  });
  console.log("Admin user seeded: olumide@greyfusion.com.ng /olu@12345");

  // 2. Seed Vehicles
  for (const v of vehicles) {
    await prisma.vehicle.upsert({
      where: { slug: v.slug },
      update: v,
      create: v,
    });
  }

  // 3. Seed Properties
  for (const p of properties) {
    await prisma.property.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }

  // 4. Seed Products
  for (const pr of products) {
    await prisma.product.upsert({
      where: { slug: pr.slug },
      update: pr,
      create: pr,
    });
  }

  // 5. Seed Projects
  for (const proj of projects) {
    await prisma.project.upsert({
      where: { slug: proj.slug },
      update: proj,
      create: proj,
    });
  }

  // 6. Seed Tenders
  for (const t of tenders) {
    await prisma.tender.upsert({
      where: { refNo: t.refNo },
      update: t,
      create: t,
    });
  }

  console.log("Database seeding completed successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });